ARG BUILD_CONFIGURATION=Release
ARG BUILD_VERSION=unknown

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION
ARG BUILD_VERSION
WORKDIR /src
COPY ["LineItem.Migrations/LineItem.Migrations.csproj", "LineItem.Migrations/"]
COPY ["LineItem.Repositories/LineItem.Repositories.csproj", "LineItem.Repositories/"]
COPY ["LineItem.Models/LineItem.Models.csproj", "LineItem.Models/"]
COPY ["LineItem.BuildVersion/LineItem.BuildVersion.csproj", "LineItem.BuildVersion/"]
RUN dotnet restore "LineItem.Migrations/LineItem.Migrations.csproj"
COPY . .
RUN dotnet publish "LineItem.Migrations/LineItem.Migrations.csproj" \
    --property:BuildVersion=$BUILD_VERSION \
    --configuration $BUILD_CONFIGURATION \
    --output /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "LineItem.Migrations.dll"]
