<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentMigrator" Version="8.0.1"/>
        <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.2"/>
        <PackageReference Include="Npgsql" Version="10.0.1"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LineItem.BuildVersion\LineItem.BuildVersion.csproj"/>
        <ProjectReference Include="..\LineItem.Repositories\LineItem.Repositories.csproj"/>
    </ItemGroup>

    <Import Project="..\LineItem.BuildVersion\BuildVersion.targets"/>

    <ItemGroup>
        <Content Include="..\LineItem.Api\appsettings*.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>appsettings (linked from LineItem.API)\%(Filename)%(Extension)</Link>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Migrations\**\*.sql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
