name: Deploy API to ECS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-migrations:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Migrations Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.migrations \
            --tag ${{ vars.AWS_ECR_MIGRATIONS_REPO_URL }}:latest \
            --push .

  migrate-database:
    if: false
    runs-on: ubuntu-latest
    needs: build-migrations
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Database Migrations
        run: |
          # Start the migration task
          TASK_ARN=$(aws ecs run-task \
            --region ${{ vars.AWS_REGION }} \
            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
            --task-definition ${{ vars.AWS_MIGRATIONS_TASK_DEFINITION_NAME }} \
            --launch-type FARGATE \
            --network-configuration '${{ vars.AWS_NETWORK_CONFIGURATION }}' \
            --query "tasks[0].taskArn" \
            --output text)
          TASK_ID=$(echo $TASK_ARN | awk -F/ '{print $NF}')
          echo "Started migrations task: $TASK_ARN"
          
          # Wait until the task enters the STOPPED state
          echo "Waiting for task to finish..."
          aws ecs wait tasks-stopped \
            --region ${{ vars.AWS_REGION }} \
            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
            --tasks "$TASK_ARN"
          
          # Wait 15 seconds for CloudWatch ingestion to finalize
          sleep 15
          
          # Output logs from the task
          echo "--- BEGIN MIGRATION LOGS ---"
          aws logs tail "${{ vars.AWS_MIGRATIONS_LOG_GROUP_NAME }}" \
            --region ${{ vars.AWS_REGION }} \
            --log-stream-name-prefix "${{ vars.AWS_MIGRATIONS_LOG_STREAM_PREFIX }}/$TASK_ID" \
            --format short
          echo "--- END MIGRATION LOGS ---"
          
          # Check if the task failed or was killed
          EXIT_CODE=$(aws ecs describe-tasks \
            --region ${{ vars.AWS_REGION }} \
            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
            --tasks "$TASK_ARN" \
            --query "tasks[0].containers[0].exitCode" \
            --output text)
          
          if [ "$EXIT_CODE" = "None" ] || [ "$EXIT_CODE" -ne 0 ]; then
            echo "Error: Migration failed or container was stopped prematurely. Exit code: $EXIT_CODE"
            exit 1
          fi
          
          echo "Task finished successfully!"
  
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push API Image
        id: build-api-image
        env:
          ECR_REPOSITORY: ${{ vars.AWS_ECR_API_REPO_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag $ECR_REPOSITORY:$IMAGE_TAG \
            --push .
          echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  
  deploy-api:
    runs-on: ubuntu-latest
    #    needs: [ build-api, migrate-database ]
    needs: build-api
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      #      - name: Download Active ECS Task Definition
      #        run: |
      #          aws ecs describe-task-definition \
      #            --task-definition my-task-definition-family \
      #            --query taskDefinition > task-definition.json

      - name: Update ECS Task Definition
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: "line-item-dev-ecs-service"
          container-name: ${{ vars.AWS_API_CONTAINER_NAME }}
          image: ${{ steps.build-api-image.outputs.image }}
      
      # 6. Deploy the updated Task Definition to the ECS Service
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          cluster: ${{ vars.AWS_ECS_CLUSTER_NAME }}
          service: ${{ vars.AWS_ECS_SERVICE_NAME }}
          wait-for-service-stability: true






# This might be able to replace all the custom code I wrote for running db migrations
#      - name: Deploy ECS Task Definition
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#        with:
#            # A boolean indicating whether to run a stand-alone task in a ECS cluster. Task will run before the service is updated if both are provided. Default value is false .
#            run-task: # optional
#            # A JSON array of container override objects which should applied when running a task outside of a service. Warning: Do not expose this field to untrusted inputs. More details: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerOverride.html
#            run-task-container-overrides: # optional
#            # A comma-separated list of security group IDs to assign to a task when run outside of a service. Will default to none.
#            run-task-security-groups: # optional
#            # A comma-separated list of subnet IDs to assign to a task when run outside of a service. Will default to none.
#            run-task-subnets: # optional
#            # Whether the task's elastic network interface receives a public IP address. The default value is DISABLED but will only be applied if run-task-subnets or run-task-security-groups are also set.
#            run-task-assign-public-IP: # optional
#            # A JSON array of capacity provider strategy items which should applied when running a task outside of a service. Will default to none.
#            run-task-capacity-provider-strategy: # optional
#            # ECS launch type for tasks run outside of a service. Valid values are 'FARGATE' or 'EC2'. Will default to 'FARGATE'. Will only be applied if run-task-capacity-provider-strategy is not set.
#            run-task-launch-type: # optional
#            # A name to use for the startedBy tag when running a task outside of a service. Will default to 'GitHub-Actions'.
#            run-task-started-by: # optional
#            # A JSON array of tags.
#            run-task-tags: # optional
#            # Whether to wait for the task to stop when running it outside of a service. Will default to not wait.
#            wait-for-task-stopped: # optional

