name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-migrations:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Migrations Image
        id: build
        run: |
          IMAGE_TAG="${{ vars.AWS_ECR_MIGRATIONS_REPO_URL  }}:${{ github.sha }}"
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.migrations \
            --tag $IMAGE_TAG \
            --push .
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

  build-api:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push API Image
        id: build
        run: |
          IMAGE_TAG="${{ vars.AWS_ECR_API_REPO_URL }}:${{ github.sha }}"
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag $IMAGE_TAG \
            --push .
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
  
  migrate-database:
    needs: build-migrations
    uses: ./.github/workflows/migrate-database-job.yml
    with:
      target-environment: dev
      image-tag: ${{ needs.build-migrations.outputs.image-tag }}
    secrets: inherit
  
  deploy-api:
    needs: [ build-api, migrate-database ]
    uses: ./.github/workflows/deploy-api-job.yml
    with:
      target-environment: dev
      image-tag: ${{ needs.build-api.outputs.image-tag }}
    secrets: inherit
