name: Shared Job - Migrate Database

on:
  workflow_call:
    inputs:
      target-environment:
        description: 'The target environment (e.g., dev, staging, prod)'
        type: string
        required: true
      image-tag:
        description: 'The Docker image tag to deploy'
        type: string
        required: true

jobs:
  migrate-database-shared-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update ECS Task Definition
        id: update-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: ${{ vars.AWS_MIGRATIONS_TASK_DEFINITION_FAMILY_NAME }}
          container-name: ${{ vars.AWS_MIGRATIONS_CONTAINER_NAME }}
          image: ${{ inputs.image-tag }}

      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.update-task.outputs.task-definition }}
          cluster: ${{ vars.AWS_ECS_CLUSTER_NAME }}
          run-task: true
          run-task-security-groups: ${{ vars.AWS_RUN_TASK_SECURITY_GROUP_ID }}
          run-task-subnets: ${{ vars.AWS_RUN_TASK_SUBNET_IDS }}
          run-task-assign-public-IP: DISABLED
          wait-for-task-stopped: true
