name: Promote

on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      image-tag:
        description: 'Image tag'
        required: true
        type: string

jobs:
  migrate-database:
    uses: ./.github/workflows/migrate-database-job.yml
    with:
      target-environment: ${{ inputs.target-environment }}
      image-tag: "${{ vars.AWS_ECR_MIGRATIONS_REPO_URL }}:${{ inputs.image-tag }}"
    secrets: inherit
  
  deploy-api:
    needs: migrate-database
    uses: ./.github/workflows/deploy-api-job.yml
    with:
      target-environment: ${{ inputs.target-environment }}
      image-tag: "${{ vars.AWS_ECR_API_REPO_URL }}:${{ inputs.image-tag }}"
    secrets: inherit
