name: Rollback Database Migrations

on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      downgrade-to-revision:
        description: 'The migration revision number to downgrade to (e.g., 0)'
        required: true
        type: string

jobs:
  rollback-migrations:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Rollback Database Migrations
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECS_CLUSTER_NAME: ${{ vars.AWS_ECS_CLUSTER_NAME }}
          TASK_DEFINITION_FAMILY: ${{ vars.AWS_MIGRATIONS_TASK_DEFINITION_FAMILY_NAME }}
          NETWORK_CONFIGURATION: ${{ vars.AWS_NETWORK_CONFIGURATION }}
          LOG_GROUP_NAME: ${{ vars.AWS_MIGRATIONS_LOG_GROUP_NAME }}
          LOG_STREAM_PREFIX: ${{ vars.AWS_MIGRATIONS_LOG_STREAM_PREFIX }}
          CONTAINER_OVERRIDES: |
            {
              "containerOverrides": [
                {
                  "name": "${{ vars.AWS_MIGRATIONS_CONTAINER_NAME }}",
                  "command": ["--downgradeToRevision=${{ inputs.downgrade-to-revision }}"]
                }
              ]
            }
        run: |
          # Get the latest task definition ARN
          TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION_FAMILY \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "Using task definition: $TASK_DEF_ARN"
          
          # Start the migration rollback task
          TASK_ARN=$(aws ecs run-task \
            --region $AWS_REGION \
            --cluster $ECS_CLUSTER_NAME \
            --task-definition $TASK_DEF_ARN \
            --launch-type FARGATE \
            --network-configuration "$NETWORK_CONFIGURATION" \
            --overrides "$CONTAINER_OVERRIDES" \
            --query "tasks[0].taskArn" \
            --output text)
          TASK_ID=$(echo $TASK_ARN | awk -F/ '{print $NF}')
          echo "Started migrations task: $TASK_ARN"

          # Wait until the task enters the STOPPED state
          echo "Waiting for task to finish..."
          aws ecs wait tasks-stopped \
            --region $AWS_REGION  \
            --cluster $ECS_CLUSTER_NAME \
            --tasks "$TASK_ARN"

          # Wait 15 seconds for CloudWatch ingestion to finalize
          sleep 15

          # Output logs from the task
          echo "--- BEGIN MIGRATION LOGS ---"
          aws logs tail "$LOG_GROUP_NAME" \
            --region $AWS_REGION \
            --log-stream-name-prefix "$LOG_STREAM_PREFIX/$TASK_ID" \
            --format short
          echo "--- END MIGRATION LOGS ---"

          # Check if the task failed or was killed
          EXIT_CODE=$(aws ecs describe-tasks \
            --region $AWS_REGION \
            --cluster $ECS_CLUSTER_NAME \
            --tasks "$TASK_ARN" \
            --query "tasks[0].containers[0].exitCode" \
            --output text)

          if [ "$EXIT_CODE" = "None" ] || [ "$EXIT_CODE" -ne 0 ]; then
            echo "Error: Migration failed or container was stopped prematurely. Exit code: $EXIT_CODE"
            exit 1
          fi

          echo "Task finished successfully!"
